import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <Link href="/" className="logo">
            JE forum
          </Link>
          <Link href="/list">리스트</Link>
          <Link href="/write">글쓰기</Link>
          <Link href="/join">회원가입</Link>
          <Link href="/login">로그인</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
