import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import LogInBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogOutBtn from "./LogoutBtn";
import DarkMode from "./DarkMode";
import { cookies } from "next/dist/client/components/headers";
// import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // 현재 로그인 된 유저이름, 이메일 등이 남음
  const session = await getServerSession(authOptions);
  // console.log("### layout 확인 : session\n", session); // { user: { name: 'INDIRA-JE', email: 'whddms87@gmail.com', image: 'https://avatars.githubusercontent.com/u/37805937?v=4' }}

  let cookie = cookies().get("mode");

  return (
    // <html lang="en">
    <html>
      <body
        className={
          cookie != undefined && cookie.value == "dark"
            ? "dark-mode"
            : "light-mode"
        }
      >
        {/* <body className={inter.className}> */}
        <div className="navbar">
          <Link href="/" className="logo">
            JE forum
          </Link>
          <Link href="/list">리스트</Link>
          <Link href="/write">글쓰기</Link>
          {/* <Link href="/join">회원가입</Link> */}
          <Link href="/register">회원가입</Link>
          {session ? (
            <span>
              {session.user.name} <LogOutBtn />
            </span>
          ) : (
            <LogInBtn />
          )}
          <DarkMode />
        </div>
        {children}
      </body>
    </html>
  );
}
